"""Curated vocabularies used by the deterministic job-description parser.

Deliberately hand-maintained rather than model-generated: the heuristic path has
to work with no API key, and predictable extraction beats broad-but-fuzzy.
"""

from __future__ import annotations

# canonical name -> alternative spellings found in real job posts
SKILLS: dict[str, list[str]] = {
    # languages
    "Python": ["python", "python3"],
    "JavaScript": ["javascript", "js", "es6"],
    "TypeScript": ["typescript", "ts"],
    "Java": ["java"],
    "Kotlin": ["kotlin"],
    "Go": ["golang", "go lang"],
    "Rust": ["rust"],
    "C++": ["c++", "cpp"],
    "C#": ["c#", "csharp", ".net", "dotnet"],
    "Ruby": ["ruby"],
    "PHP": ["php"],
    "Scala": ["scala"],
    "Swift": ["swift"],
    "SQL": ["sql"],
    "R": [],
    "Haskell": ["haskell"],
    "Elixir": ["elixir"],
    "Bash": ["bash", "shell scripting"],
    # backend / frameworks
    "Django": ["django"],
    "Flask": ["flask"],
    "FastAPI": ["fastapi", "fast api"],
    "Node.js": ["node.js", "nodejs", "node js"],
    "Express": ["express.js", "expressjs"],
    "Spring Boot": ["spring boot", "springboot", "spring"],
    "Rails": ["rails", "ruby on rails"],
    "Laravel": ["laravel"],
    ".NET Core": ["asp.net", "dotnet core"],
    "GraphQL": ["graphql"],
    "gRPC": ["grpc"],
    "REST APIs": ["rest api", "restful", "rest apis"],
    "Microservices": ["microservice", "microservices"],
    "Event-Driven Architecture": ["event driven", "event-driven"],
    # frontend
    "React": ["react", "react.js", "reactjs"],
    "Next.js": ["next.js", "nextjs"],
    "Vue.js": ["vue", "vue.js", "vuejs"],
    "Angular": ["angular", "angularjs"],
    "Svelte": ["svelte", "sveltekit"],
    "Redux": ["redux"],
    "Tailwind CSS": ["tailwind", "tailwindcss"],
    "HTML": ["html", "html5"],
    "CSS": ["css", "css3", "scss", "sass"],
    "React Native": ["react native"],
    "Flutter": ["flutter"],
    "Android": ["android"],
    "iOS": ["ios"],
    "Accessibility": ["accessibility", "a11y", "wcag"],
    # data / infra
    "PostgreSQL": ["postgresql", "postgres"],
    "MySQL": ["mysql", "mariadb"],
    "MongoDB": ["mongodb", "mongo"],
    "Redis": ["redis"],
    "Elasticsearch": ["elasticsearch", "opensearch"],
    "Cassandra": ["cassandra"],
    "DynamoDB": ["dynamodb"],
    "Kafka": ["kafka"],
    "RabbitMQ": ["rabbitmq"],
    "Snowflake": ["snowflake"],
    "BigQuery": ["bigquery"],
    "Redshift": ["redshift"],
    "Databricks": ["databricks"],
    "Spark": ["spark", "pyspark", "apache spark"],
    "Airflow": ["airflow"],
    "dbt": ["dbt"],
    "ETL": ["etl", "elt"],
    "Data Modelling": ["data modeling", "data modelling"],
    "Data Warehousing": ["data warehouse", "data warehousing"],
    # cloud / devops
    "AWS": ["aws", "amazon web services"],
    "GCP": ["gcp", "google cloud"],
    "Azure": ["azure"],
    "Kubernetes": ["kubernetes", "k8s", "eks", "gke"],
    "Docker": ["docker", "containerization", "containerisation"],
    "Terraform": ["terraform"],
    "Ansible": ["ansible"],
    "CI/CD": ["ci/cd", "cicd", "continuous integration", "continuous delivery"],
    "Jenkins": ["jenkins"],
    "GitHub Actions": ["github actions"],
    "Linux": ["linux", "unix"],
    "Observability": [
        "observability",
        "monitoring",
        "prometheus",
        "grafana",
        "datadog",
    ],
    "Site Reliability": ["sre", "site reliability"],
    "Serverless": ["serverless", "lambda functions"],
    "Nginx": ["nginx"],
    # ml / ai
    "Machine Learning": ["machine learning", "ml"],
    "Deep Learning": ["deep learning"],
    "PyTorch": ["pytorch"],
    "TensorFlow": ["tensorflow"],
    "scikit-learn": ["scikit-learn", "sklearn"],
    "NLP": ["nlp", "natural language processing"],
    "Computer Vision": ["computer vision", "opencv"],
    "LLMs": ["llm", "llms", "large language model", "generative ai", "genai"],
    "RAG": ["rag", "retrieval augmented"],
    "MLOps": ["mlops"],
    "Recommendation Systems": ["recommendation system", "recsys"],
    "Statistics": ["statistics", "statistical modeling"],
    "Pandas": ["pandas"],
    "NumPy": ["numpy"],
    # quality / practice
    "System Design": ["system design", "distributed systems"],
    "Unit Testing": ["unit test", "unit testing", "pytest", "jest"],
    "Test Automation": ["test automation", "selenium", "cypress", "playwright"],
    "Performance Tuning": ["performance tuning", "performance optimization"],
    "Security": ["security", "appsec", "owasp"],
    "Agile": ["agile", "scrum", "kanban"],
    "Git": ["git", "github", "gitlab", "version control"],
    "Code Review": ["code review"],
    "Technical Leadership": ["tech lead", "technical leadership", "mentoring"],
    # product / design / business
    "Product Management": ["product management", "product manager"],
    "Roadmapping": ["roadmap", "roadmapping"],
    "A/B Testing": ["a/b test", "ab testing", "experimentation"],
    "SQL Analytics": ["analytics", "data analysis"],
    "Figma": ["figma"],
    "UX Research": ["ux research", "user research"],
    "UI Design": ["ui design", "visual design"],
    "Salesforce": ["salesforce"],
    "HubSpot": ["hubspot"],
    "SEO": ["seo"],
    "Content Marketing": ["content marketing"],
    "Financial Modelling": ["financial modeling", "financial modelling"],
    "Excel": ["excel", "advanced excel"],
    "Stakeholder Management": ["stakeholder management"],
    "Customer Success": ["customer success"],
    "Recruiting": ["recruiting", "talent acquisition", "sourcing"],
}

SENIORITY_MARKERS: dict[str, list[str]] = {
    "entry": [
        "intern",
        "fresher",
        "graduate",
        "entry level",
        "entry-level",
        "junior",
        "trainee",
    ],
    "mid": ["mid level", "mid-level", "software engineer ii", "associate"],
    "senior": ["senior", "sr.", "sr ", "experienced"],
    "manager": [
        "lead",
        "staff",
        "principal",
        "engineering manager",
        "team lead",
        "manager",
    ],
    "director": ["director", "head of"],
    "vp": ["vice president", "vp of", "vp,"],
    "cxo": ["cto", "ceo", "chief technology", "chief product", "founder"],
}

TITLE_SYNONYMS: dict[str, list[str]] = {
    "backend engineer": [
        "Backend Engineer",
        "Software Engineer",
        "Backend Developer",
        "Server Engineer",
    ],
    "frontend engineer": [
        "Frontend Engineer",
        "Frontend Developer",
        "UI Engineer",
        "Web Developer",
    ],
    "full stack engineer": [
        "Full Stack Engineer",
        "Full Stack Developer",
        "Software Engineer",
    ],
    "software engineer": [
        "Software Engineer",
        "Software Developer",
        "Backend Engineer",
        "Application Developer",
    ],
    "data engineer": [
        "Data Engineer",
        "Analytics Engineer",
        "ETL Developer",
        "Big Data Engineer",
    ],
    "data scientist": [
        "Data Scientist",
        "Machine Learning Scientist",
        "Applied Scientist",
    ],
    "machine learning engineer": [
        "Machine Learning Engineer",
        "ML Engineer",
        "AI Engineer",
        "Applied ML Engineer",
    ],
    "devops engineer": [
        "DevOps Engineer",
        "Site Reliability Engineer",
        "Platform Engineer",
        "Infrastructure Engineer",
    ],
    "sre": ["Site Reliability Engineer", "DevOps Engineer", "Production Engineer"],
    "mobile engineer": [
        "Mobile Engineer",
        "Android Developer",
        "iOS Developer",
        "React Native Developer",
    ],
    "qa engineer": ["QA Engineer", "SDET", "Test Engineer", "Automation Engineer"],
    "product manager": [
        "Product Manager",
        "Associate Product Manager",
        "Technical Product Manager",
    ],
    "designer": ["Product Designer", "UX Designer", "UI Designer"],
    "data analyst": ["Data Analyst", "Business Analyst", "Analytics Specialist"],
    "solutions architect": [
        "Solutions Architect",
        "Solution Architect",
        "Technical Architect",
    ],
    "security engineer": [
        "Security Engineer",
        "Application Security Engineer",
        "InfoSec Engineer",
    ],
    "sales": ["Account Executive", "Sales Manager", "Business Development Manager"],
    "recruiter": ["Recruiter", "Talent Acquisition Specialist", "Technical Recruiter"],
}

# city / region -> ISO-3166 alpha-2
LOCATIONS: dict[str, str] = {
    "bengaluru": "IN",
    "bangalore": "IN",
    "hyderabad": "IN",
    "pune": "IN",
    "mumbai": "IN",
    "delhi": "IN",
    "new delhi": "IN",
    "gurugram": "IN",
    "gurgaon": "IN",
    "noida": "IN",
    "chennai": "IN",
    "kolkata": "IN",
    "ahmedabad": "IN",
    "jaipur": "IN",
    "kochi": "IN",
    "coimbatore": "IN",
    "indore": "IN",
    "chandigarh": "IN",
    "india": "IN",
    "san francisco": "US",
    "bay area": "US",
    "new york": "US",
    "nyc": "US",
    "seattle": "US",
    "austin": "US",
    "boston": "US",
    "chicago": "US",
    "los angeles": "US",
    "denver": "US",
    "united states": "US",
    "usa": "US",
    "london": "GB",
    "manchester": "GB",
    "united kingdom": "GB",
    "riyadh": "SA",
    "jeddah": "SA",
    "saudi arabia": "SA",
    "dubai": "AE",
    "singapore": "SG",
    "berlin": "DE",
    "amsterdam": "NL",
    "toronto": "CA",
    "vancouver": "CA",
    "sydney": "AU",
    "melbourne": "AU",
}

DEGREE_MARKERS = [
    "b.tech",
    "btech",
    "b.e.",
    "be/btech",
    "bachelor",
    "b.sc",
    "bsc",
    "m.tech",
    "mtech",
    "master",
    "m.sc",
    "msc",
    "mca",
    "bca",
    "mba",
    "phd",
    "ph.d",
    "doctorate",
]

# Section headings that flip subsequent bullets from must-have to nice-to-have.
NICE_TO_HAVE_HEADINGS = [
    "nice to have",
    "nice-to-have",
    "good to have",
    "bonus",
    "preferred",
    "plus points",
    "a plus",
    "desirable",
    "optional",
    "we'd love",
    "wed love",
    "icing on the cake",
    "brownie points",
]

MUST_HAVE_HEADINGS = [
    "requirement",
    "must have",
    "must-have",
    "what you'll need",
    "what you need",
    "qualification",
    "you should have",
    "we are looking for",
    "we're looking for",
    "who you are",
    # Heading-shaped only: a bare "skills" also matches bullets like
    # "excellent communication skills" and would flip the section back.
    "required skills",
    "key skills",
    "technical skills",
    "skills & experience",
    "skills and experience",
    "essential",
    "you bring",
    "minimum qualification",
]

RESPONSIBILITY_HEADINGS = [
    "responsibilit",
    "what you'll do",
    "what you will do",
    "the role",
    "about the role",
    "your mission",
    "day to day",
    "day-to-day",
]

WORK_MODES = {
    "remote": [
        "fully remote",
        "remote-first",
        "remote first",
        "work from home",
        "wfh",
        "remote",
    ],
    "hybrid": ["hybrid"],
    "onsite": ["on-site", "onsite", "in-office", "work from office", "wfo"],
}

EMPLOYMENT_TYPES = {
    "Full-time": ["full time", "full-time", "permanent"],
    "Contract": ["contract", "contractor", "freelance", "consultant"],
    "Internship": ["internship", "intern"],
    "Part-time": ["part time", "part-time"],
}
